import {fields,match,normalizeJobs,filterJobs} from './career-core.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
let profile=read('career-profile',{}), jobs=[], status='', busy=false;
try { const cached=read('career-feed',null); if(cached){jobs=normalizeJobs(cached.jobs);status='Cached results retrieved '+new Date(cached.at).toLocaleString()+'. Refresh to check current availability.';} } catch {}
let preferences=read('career-search',{resume:read('aigyaan-resume-builder',{}).sourceText||'',query:'',location:'',days:7,min:0});
const boards=['LinkedIn','Naukri','Monsterjobs','Foundit','Cutshort','GetSmart','Indeed','Company careers'];
const guides={
 'Data Analyst':[['SQL joins and aggregation','How do you retain customers with no orders?',['LEFT JOIN from customers','INNER JOIN from orders','CROSS JOIN'],0,'A left join preserves every customer; unmatched order columns are NULL.'],['Metrics and experiments','Which metric best measures repeat usage?',['Page colour','Retention by cohort','Total rows'],1,'Cohort retention tracks whether the same group returns over time.']],
 'Frontend Engineer':[['Accessible interfaces','What gives a form field an accessible name?',['Placeholder alone','An associated label','A CSS class'],1,'Associate a label using for/id, or wrap the input in a label.'],['State and effects','Where should a network request run in React?',['During every render','In an effect or data layer','In a CSS file'],1,'Use an effect or framework data layer, including cancellation and error states.']],
 'Generative AI Engineer':[['Retrieval and evaluation','How do you evaluate a RAG answer?',['Length only','Groundedness and retrieval relevance','Font size'],1,'Measure retrieval relevance, factual grounding, and task success on a held-out set.'],['Model reliability','What should happen when evidence is missing?',['Invent a source','State uncertainty or abstain','Repeat the question'],1,'Use an explicit uncertainty path and collect evidence before making claims.']],
 'AI Product Manager':[['Product outcomes','What is a useful success measure?',['Number of meetings','User task success','Lines of code'],1,'Choose a measurable user outcome with cost and safety guardrails.'],['Prioritisation','How should you prioritise a feature?',['Evidence, impact and effort','The loudest request','Alphabetically'],0,'Compare evidence, expected impact, implementation cost, and risks.']],
 'Cloud Engineer':[['Resilience','How do you reduce a single-zone failure risk?',['Multi-zone deployment','One larger server','Remove monitoring'],0,'Distribute workloads across zones and test failover.'],['Identity','What does least privilege mean?',['Administrator for all','Only necessary permissions','Shared credentials'],1,'Grant only the actions and resources a workload requires.']],
 'Business Analyst':[['Requirements','What makes acceptance criteria useful?',['Vague expectations','Observable testable outcomes','A long document'],1,'Describe observable outcomes and edge cases so stakeholders can verify completion.'],['Stakeholder analysis','How do you resolve conflicting requirements?',['Ignore one team','Clarify goals and agree tradeoffs','Build both immediately'],1,'Document objectives, constraints and tradeoffs, then agree priorities.']]
};
export function careerView(view){
 if(view==='candidate')return `<section class="career-page"><p class="eyebrow">Your application passport</p><h1>Tell us once. Apply with confidence.</h1><p>Saved on this browser until you delete it. Export your answers to the Chrome extension to reuse them beside application forms.</p><label>Import saved answers (.json)<input type="file" id="profileImport" accept=".json"></label><form id="candidateForm" class="resume-section"><div class="resume-field-grid">${Object.entries(fields).map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(profile[key])}" ${key==='email'?'type="email"':''}></label>`).join('')}</div><p>Company-specific employment history, eligibility and declarations are asked on the application. They are never guessed.</p><div class="download-row"><button class="primary-btn">Save details</button><button type="button" class="ghost-btn" id="exportProfile">Export for extension</button><button type="button" class="ghost-btn" id="deleteProfile">Delete saved details</button></div><p id="profileStatus" role="status"></p></form><article class="resume-section"><h2>Your application companion</h2><p>Download and unzip the extension. In Chrome, open chrome://extensions, enable Developer mode, choose Load unpacked and select the extracted extension folder. Import your exported profile, open an application page, then click the extension icon.</p><a class="primary-btn" href="./extension.zip" download>Download Chrome extension</a><p>The side panel keeps answers visible. Fill supported empty fields with one click, or enable filling as fields appear. Review the form and submit yourself. Custom widgets and cross-origin frames may need manual entry.</p></article></section>`;
 if(view==='prep')return `<section class="career-page"><p class="eyebrow">Interview studio</p><h1>Turn a match into an offer.</h1><p>Original practice guides and quizzes. Choose a role, study the explanation, then test yourself.</p><label>Job role<select id="prepRole">${Object.keys(guides).map(r=>`<option>${r}</option>`).join('')}</select></label><div id="guideContent"></div></section>`;
 return `<section class="career-page"><p class="eyebrow">Your next chapter starts here</p><h1>Less searching.<br>More right-fit opportunities.</h1><p>Find recent roles, understand your match, and prepare an application that sounds like you.</p><div class="career-stats"><article><strong>01</strong><span>Add your experience</span></article><article><strong>02</strong><span>Find your fit</span></article><article><strong>03</strong><span>Prepare & apply</span></article></div><form id="careerSearch" class="resume-section"><div class="resume-field-grid"><label>Role or keyword<input name="query" value="${esc(preferences.query)}" placeholder="Data Analyst"></label><label>Location contains<input name="location" value="${esc(preferences.location)}" placeholder="India, worldwide…"></label><label>Posted within<select name="days">${[1,3,7,14,30,90].map(n=>`<option value="${n}" ${+preferences.days===n?'selected':''}>${n} day${n>1?'s':''}</option>`).join('')}</select></label><label>Minimum skill match<select name="min">${[0,25,50,75,90].map(n=>`<option value="${n}" ${+preferences.min===n?'selected':''}>${n}%</option>`).join('')}</select></label></div><label>Your CV text<textarea name="resume" placeholder="Paste your experience and skills for matching">${esc(preferences.resume)}</textarea></label><label>Or upload a text CV<input type="file" id="careerCv" accept=".txt"></label><div class="download-row"><button class="primary-btn" ${busy?'disabled':''}>${busy?'Loading…':'Find live remote jobs'}</button><button type="button" class="ghost-btn" id="filterJobs">Apply filters</button><label class="ghost-btn">Import job feed (.json)<input id="jobImport" type="file" accept=".json"></label></div><small>Live feed: Remotive, with source publication dates; listings are delayed by 24 hours. CV stays in this browser. Match is keyword coverage, not a hiring probability.</small></form><p id="careerStatus" role="status">${esc(status)}</p><div id="careerResults"></div><article class="resume-section"><h2>Search across your favourite platforms</h2><p>These open searches, not aggregated vacancies. Verify dates and availability on each site.</p><div class="board-links">${boards.map(b=>`<a target="_blank" rel="noreferrer" data-board="${b}">${b} ↗</a>`).join('')}</div></article><article class="resume-section"><h2>Tailor your application</h2><form id="letterForm"><div class="resume-field-grid"><label>Company<input name="company" required></label><label>Role<input name="role" required></label></div><label>Job description<textarea name="description" required></textarea></label><button class="primary-btn">Prepare cover letter & gap review</button></form><div id="letterOutput"></div><button class="ghost-btn" data-view="resume">Open CV builder →</button></article></section>`;
}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'text/plain'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function capture(){const form=document.querySelector('#careerSearch');if(form){preferences=Object.fromEntries(new FormData(form));localStorage.setItem('career-search',JSON.stringify(preferences));}}
function results(){const target=document.querySelector('#careerResults');if(!target)return;const list=filterJobs(jobs,preferences);target.innerHTML=list.length?list.map(j=>`<article class="job-card"><div class="job-card-head"><div><span class="source-pill">${esc(j.source)} · ${esc(new Date(j.postedAt).toLocaleDateString())}</span><h2>${esc(j.title)}</h2><p>${esc(j.company)} · ${esc(j.location)}</p></div><span class="match-score">${j.score===null?'N/A':j.score+'%'}</span></div><p>Matched skills: ${esc(j.matched.join(', ')||'None detected')}</p><p>Not evidenced in CV: ${esc(j.missing.join(', ')||'No gaps in recognised keywords')}</p><small>Add evidence only for skills you have; use remaining gaps as a learning plan.</small><a class="primary-btn job-link" href="${esc(j.url)}" target="_blank" rel="noreferrer">Review & apply on ${esc(j.source)} ↗</a></article>`).join(''):'<div class="resume-section"><h2>No matching listings yet</h2><p>Load the live feed, import a dated job feed, or widen your filters.</p></div>';const domains=['linkedin.com/jobs','naukri.com','monster.com','foundit.in','cutshort.io','getsmart','indeed.com','careers'];document.querySelectorAll('[data-board]').forEach((a,i)=>{a.href='https://www.google.com/search?q='+encodeURIComponent(`${i===5||i===7?domains[i]:'site:'+domains[i]} ${preferences.query} ${preferences.location} jobs`);});}
export function bindCareer(view){
 const form=document.querySelector('#candidateForm');
 document.querySelector('#profileImport')?.addEventListener('change',async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100000)throw Error();const data=JSON.parse(await f.text());if(!data||typeof data!=='object'||Array.isArray(data))throw Error();profile=Object.fromEntries(Object.keys(fields).filter(k=>typeof data[k]==='string').map(k=>[k,data[k].slice(0,500)]));localStorage.setItem('career-profile',JSON.stringify(profile));for(const input of form.querySelectorAll('input'))input.value=profile[input.name]||'';document.querySelector('#profileStatus').textContent='Answers imported and saved on this browser.';}catch{document.querySelector('#profileStatus').textContent='Could not import. Choose a valid application profile JSON.';}});
 form?.addEventListener('submit',e=>{e.preventDefault();profile=Object.fromEntries(new FormData(form));localStorage.setItem('career-profile',JSON.stringify(profile));document.querySelector('#profileStatus').textContent='Saved on this browser.';});
 document.querySelector('#exportProfile')?.addEventListener('click',()=>download('application-profile.json',JSON.stringify(Object.fromEntries(new FormData(form)),null,2)));
 document.querySelector('#deleteProfile')?.addEventListener('click',()=>{localStorage.removeItem('career-profile');profile={};form.reset();form.querySelectorAll('input').forEach(i=>i.value='');document.querySelector('#profileStatus').textContent='Saved details deleted.';});
 function showGuide(){const role=document.querySelector('#prepRole').value;document.querySelector('#guideContent').innerHTML=guides[role].map(([topic,q,answers,correct,explanation],i)=>`<article class="resume-section"><h2>${topic}</h2><p>Prepare a real example from your work, explain your decision, and describe how you measured the outcome.</p><h3>${q}</h3><div class="download-row">${answers.map((a,n)=>`<button class="ghost-btn quiz-answer" data-correct="${n===correct}" data-question="${i}">${a}</button>`).join('')}</div><p id="quiz${i}" role="status"></p><details><summary>Study the answer</summary><p>${explanation}</p></details></article>`).join('');document.querySelectorAll('.quiz-answer').forEach(b=>b.onclick=()=>{document.querySelector('#quiz'+b.dataset.question).textContent=b.dataset.correct==='true'?'Correct. '+guides[role][+b.dataset.question][4]:'Try again. Review the guide for a hint.';});}
 if(view==='prep'){showGuide();document.querySelector('#prepRole').onchange=showGuide;}
 document.querySelector('#careerCv')?.addEventListener('change',async e=>{const f=e.target.files[0];if(f&&f.size<1000000)document.querySelector('[name=resume]').value=await f.text();capture();results();});
 document.querySelector('#careerSearch')?.addEventListener('submit',async e=>{e.preventDefault();capture();busy=true;const button=e.submitter;button.disabled=true;document.querySelector('#careerStatus').textContent='Loading live listings…';try{let cached=read('career-feed',null);if(!cached||Date.now()-cached.at>21600000){const r=await fetch('https://remotive.com/api/remote-jobs',{signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Feed unavailable');const data=await r.json();cached={at:Date.now(),jobs:normalizeJobs(data.jobs.map(j=>({...j,source:'Remotive'})))};try{localStorage.setItem('career-feed',JSON.stringify(cached));}catch{/* Listings remain available when storage is full. */}}jobs=normalizeJobs(cached.jobs);status=`${jobs.length} live-source listings loaded. Last retrieved ${new Date(cached.at).toLocaleString()}.`; }catch{status='Could not load the live feed. Retry later, import a job feed, or use the board searches below.';}finally{busy=false;button.disabled=false;const s=document.querySelector('#careerStatus');if(s)s.textContent=status;results();}});
 document.querySelector('#filterJobs')?.addEventListener('click',()=>{capture();results();});
 document.querySelector('#jobImport')?.addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error('File too large');const raw=JSON.parse(await file.text());jobs=normalizeJobs(Array.isArray(raw)?raw:raw.jobs);capture();status=`Imported ${jobs.length} listings with valid URLs and dates.`;results();}catch{status='Invalid feed. Use a JSON jobs array with title, description, url and postedAt.';}document.querySelector('#careerStatus').textContent=status;});
 document.querySelector('#letterForm')?.addEventListener('submit',e=>{e.preventDefault();capture();const v=Object.fromEntries(new FormData(e.target)),fit=match(preferences.resume,v.description);const letter=`Dear Hiring Manager,\n\nI am applying for the ${v.role} role at ${v.company}. ${fit.matched.length?'My CV includes experience with '+fit.matched.join(', ')+'.':'Please review my attached CV for my experience.'}\n\n[Add a specific, verified achievement relevant to this role.]\n\nI would welcome the opportunity to discuss how my experience could contribute to your team. Thank you for considering my application.\n\nKind regards,\n${[profile.firstName,profile.lastName].filter(Boolean).join(' ')||'[Your name]'}\n${profile.email||''}`;document.querySelector('#letterOutput').innerHTML=`<p>Missing evidence: ${esc(fit.missing.join(', ')||'No recognised keyword gaps')}. Review requirements beyond keywords too.</p><label>Editable cover-letter draft<textarea id="letterDraft"></textarea></label><button class="ghost-btn" id="downloadLetter">Download draft</button>`;document.querySelector('#letterDraft').value=letter;document.querySelector('#downloadLetter').onclick=()=>download('cover-letter.txt',document.querySelector('#letterDraft').value);});results();
}
